name: Deploy Fake
on:
    workflow_call:
        secrets:
            ambiente:
                required: true
                description: "Ambiente aonde será feito o deploy"
jobs:
    deploy-kubernetes:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ secrets.ambiente }}"
            - name: curl Deploy no ambiente
              run: "curl -X POST https://webhook.site/d01f2e19-d1b2-41f1-a8a0-7d64ae1d2a49 -d '{ambiente: ${{ secrets.ambiente }}}'"                  



              